package main

import (
	"io/ioutil"
	"os"
	"strings"
)

func main() {
	b, err := ioutil.ReadFile("src/toggl_api.h")
	if err != nil {
		println(err.Error())
		os.Exit(1)
	}
	l := strings.Split(string(b), "\n")
	var out []string
	write := func(s string) {
		out = append(out, s)
	}
	// output warning
	write("// Warning: this file is autogenerated! do not modify, all changes will be lost!")
	for _, s := range l {
		println(s)
		// all comments will go through
		if strings.Contains(s, "//") {
			// except for #ifdef
			if !strings.Contains(s, "#") {
				write(s)
			}
		}
		
	}
	println("----------- toggl_api.cs -------------")
	for _, s := range out {
		println(s)
	}
}