source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.11'
use_frameworks!
inhibit_all_warnings!

def essential_pods
  pod 'GTMAppAuth'
  pod 'AppAuth'
  pod 'MASShortcut'
  pod 'Bugsnag'
end

# TogglDesktop
target 'TogglDesktop' do
  project 'TogglDesktop/TogglDesktop.xcodeproj'
  essential_pods
  pod 'Sparkle'
end

# TogglDesktop-AppStore
target 'TogglDesktop-AppStore' do
  project 'TogglDesktop/TogglDesktop.xcodeproj'
  essential_pods
end
