disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol
  - colon
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - legacy_constant
  - legacy_constructor
  - line_length
  - nesting
  - redundant_string_enum_value
  - shorthand_operator
  - todo
  - type_body_length
  - valid_ibinspectable
  - large_tuple
  - identifier_name

opt_in_rules: # some rules are only opt-in

# TODO: Consider those
#  - toggle_bool
#  - modifier_order
#  - first_where
#  - fatal_error_message
#  - empty_string

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - TogglDesktopLibrary/Dependencies
  - Features/ColorWheel
