disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - nesting
  - todo
  - type_body_length
  - large_tuple
  - vertical_parameter_alignment
  - cyclomatic_complexity

opt_in_rules: # some rules are only opt-in

# TODO: Consider enabling those
#  - toggle_bool
#  - modifier_order
#  - first_where
#  - fatal_error_message
#  - empty_string

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - TogglDesktopLibrary/Dependencies
  - Features/ColorWheel

# configurable rules can be customized from this configuration file
line_length:
  warning: 150
  error: 250
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

identifier_name:
  min_length: 1
  max_length: 60
