// Copyright 2015 Toggl Desktop developers.

// Do not modify contents. Content is generated by running
// go run src/script/update_help_artices.go

#include "../src/help_article.h"

namespace toggl {

}   // namespace toggl
