name: PR Lint
on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    # Install your linters here
    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        swiftlint: true
